let people=[['@haru','#cb6751',32,14,86],['@mori','#648f62',25,8,79],['@nagi','#e2a84b',18,9,73],['@ito','#8d71b9',14,6,68],['@sora','#4f9da7',11,5,61],['@yui','#d37b96',9,7,64]];
const mosaic=document.querySelector('#mosaic'),create=document.querySelector('#create'),intro=document.querySelector('#intro'),exp=document.querySelector('#experience'),clusterMap=document.querySelector('#clusterMap'),reasonCard=document.querySelector('#reasonCard'),caption=document.querySelector('#caption');
const grid=18;let targetCanvas=null;

const xImageLarge=url=>(url||'').replace(/_normal(?=\.[a-z]+(?:\?|$))/i,'_400x400');

// A real chosen icon is sampled cell by cell. X OAuth will supply the same image URL later.
const upload=document.createElement('label');upload.className='primary upload-icon';upload.innerHTML='アイコンを選んで、縁を結ぶ <span>→</span><input type="file" accept="image/*">';
const demo=document.createElement('button');demo.className='demo-link';demo.textContent='デモを見る';create.replaceWith(demo);intro.querySelector('.note').before(upload);intro.querySelector('.orb').textContent='あなた';
const xButton=document.createElement('button');xButton.className='x-login';xButton.innerHTML='<strong>𝕏</strong> でえにし像を結ぶ';intro.querySelector('.orb').after(xButton);
xButton.onclick=async()=>{xButton.disabled=true;xButton.textContent='Xへ接続しています…';try{const r=await fetch('/api/x/login'),data=await r.json();if(!r.ok)throw new Error(data.error);location.href=data.authUrl}catch(error){xButton.disabled=false;xButton.innerHTML='<strong>𝕏</strong> でえにし像を結ぶ';alert('X連携の準備中です。運営者がX APIの設定を完了すると利用できます。')}};
upload.querySelector('input').onchange=e=>{const file=e.target.files[0];if(!file)return;const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{targetCanvas=document.createElement('canvas');targetCanvas.width=targetCanvas.height=200;targetCanvas.getContext('2d').drawImage(img,0,0,200,200);mosaic.style.setProperty('--portrait',`url("${url}")`);intro.querySelector('.orb').style.backgroundImage=`url(${url})`;intro.querySelector('.orb').textContent='';reveal()};img.src=url};

function fallbackTone(x,y){const face=((x-9.5)**2/40)+((y-10.5)**2/58)<1,hair=y<8&&((x-9.5)**2/48)+((y-7.5)**2/28)<1,shirt=y>16&&x>4&&x<15,eye=y===11&&(x===7||x===12),mouth=y===14&&x>8&&x<11;if(eye||mouth)return '#3d4540';if(hair)return '#424b44';if(shirt)return '#8d71b9';if(face)return '#e7a17e';return '#b7d1bb'}
function targetTone(x,y){if(!targetCanvas)return fallbackTone(x,y);const at=Math.min(199,Math.floor((x+.5)*200/grid)),p=targetCanvas.getContext('2d').getImageData(at,Math.min(199,Math.floor((y+.5)*200/grid)),1,1).data,light=(p[0]+p[1]+p[2])/3;if(light>228)return '#fffdf8';if(light<72)return '#272122';return `rgb(${p[0]},${p[1]},${p[2]})`}
function buildMosaic(){mosaic.replaceChildren();for(let y=0;y<grid;y++)for(let x=0;x<grid;x++){const p=people[(x*3+y*5+Math.floor(Math.random()*4))%people.length],t=document.createElement('button'),a=document.createElement('span'),tone=targetTone(x,y);t.className='tile';t.title=p[0];a.className='tile-avatar';t.style.setProperty('--target',tone);t.style.setProperty('--person',p[1]);if(p[5]){a.classList.add('real-avatar');a.style.backgroundImage=`url("${xImageLarge(p[5])}")`}t.style.setProperty('--scale',.94+Math.random()*.08);t.append(a);t.onclick=()=>selectPerson(p,t);mosaic.append(t)}}
function selectPerson(p,t){document.querySelectorAll('.tile.selected').forEach(x=>x.classList.remove('selected'));t?.classList.add('selected');document.querySelector('#personName').textContent=p[0];document.querySelector('#personRole').textContent='あなたの縁を近くで形づくる人';document.querySelector('#replies').textContent=`${p[2]} 回`;document.querySelector('#mutuals').textContent=`${p[3]} 人`;document.querySelector('#affinity').textContent=`${p[4]}%`}
function buildClusters(){clusterMap.replaceChildren();const spots=[[11,25,150],[58,12,105],[38,52,130],[69,63,92],[13,72,80],[76,34,66]],svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.classList.add('cluster-links');[[18,40,44,65],[44,65,72,73],[44,65,62,22],[62,22,79,42],[18,40,62,22]].forEach(q=>{const l=document.createElementNS('http://www.w3.org/2000/svg','line');l.setAttribute('x1',`${q[0]}%`);l.setAttribute('y1',`${q[1]}%`);l.setAttribute('x2',`${q[2]}%`);l.setAttribute('y2',`${q[3]}%`);svg.append(l)});clusterMap.append(svg);people.slice(0,6).forEach((p,i)=>{const c=document.createElement('button'),a=document.createElement('span'),n=document.createElement('span'),[l,t,s]=spots[i];c.className='cluster';c.dataset.label=p[0];c.style.cssText=`--color:${p[1]};--size:${s}px;left:${l}%;top:${t}%`;a.className='cluster-avatar';if(p[5]){a.classList.add('real-avatar');a.style.backgroundImage=`url("${xImageLarge(p[5])}")`}n.className='count';n.textContent='X';c.append(a,n);c.onclick=()=>{show('reasons');selectPerson(p)};clusterMap.append(c)})}
function show(view){document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.view===view));mosaic.classList.toggle('hidden',view!=='mosaic');clusterMap.classList.toggle('hidden',view!=='clusters');reasonCard.classList.toggle('hidden',view!=='reasons');document.querySelector('#resultLabel').classList.toggle('hidden',view!=='mosaic');caption.textContent={mosaic:'48人の縁が、あなたの像を結んでいます。',clusters:'近い縁ほど、太い線でつながっています。',reasons:'ひとつひとつの縁が、あなたを形づくる。'}[view]}
function reveal(){document.querySelector('.app-shell').classList.add('has-result');intro.classList.add('hidden');exp.classList.remove('hidden');buildMosaic();buildClusters()}
demo.onclick=reveal;document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>show(t.dataset.view));document.querySelector('#refresh').onclick=()=>{buildMosaic();caption.textContent='いまの縁を、もう一度結び直しました。'};
if(new URLSearchParams(location.search).get('x')==='connected'){fetch('/api/x/network').then(r=>r.json()).then(data=>{if(!data.me||!data.people?.length)throw new Error('profile');const colors=['#cb6751','#648f62','#e2a84b','#8d71b9','#4f9da7','#d37b96'];people=data.people.slice(0,20).map((p,i)=>[`@${p.username}`,colors[i%colors.length],'—','—','—',xImageLarge(p.profile_image_url)]);const count=people.length;document.querySelector('#resultLabel strong').textContent=`${count}人の縁`;caption.textContent=`${count}人の実際のアイコンが、あなたの像を結んでいます。`;const image=new Image();image.crossOrigin='anonymous';image.onload=()=>{targetCanvas=document.createElement('canvas');targetCanvas.width=targetCanvas.height=360;targetCanvas.getContext('2d').drawImage(image,0,0,360,360);reveal()};image.onerror=()=>{throw new Error('image')};image.src=xImageLarge(data.me.profile_image_url)}).catch(()=>alert('Xプロフィールを取得できませんでした。'))}
function makeShareImage(){const size=1200,pad=95,tile=(size-pad*2)/grid,c=document.createElement('canvas');c.width=c.height=size;const x=c.getContext('2d');x.fillStyle='#f5f0e7';x.fillRect(0,0,size,size);x.fillStyle='#49745a';x.font='700 30px sans-serif';x.fillText('ENISHI-ZO',pad,72);x.fillStyle='#27322c';x.font='70px serif';x.fillText('えにし像',pad,150);[...mosaic.children].forEach((n,i)=>{const a=i%grid,b=Math.floor(i/grid),s=getComputedStyle(n);x.fillStyle=s.getPropertyValue('--target');x.fillRect(pad+a*tile,pad+180+b*tile,tile-3,tile-3)});x.fillStyle='#7e8278';x.font='30px sans-serif';x.fillText('つながりが、あなたの輪郭になる。',pad,size-55);return new Promise(r=>c.toBlob(r,'image/png'))}
document.querySelector('#share').onclick=async()=>{const blob=await makeShareImage(),file=new File([blob],'enishi-zo.png',{type:'image/png'}),text='私を形づくる縁を結んだ、えにし像。 #えにし像';try{if(navigator.canShare?.({files:[file]}))await navigator.share({title:'えにし像',text,files:[file]});else{const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='enishi-zo.png';a.click();URL.revokeObjectURL(a.href)}}catch(e){if(e.name!=='AbortError')console.error(e)}};
